# Generated by Django 5.1 on 2024-09-02 17:39

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('created_at', models.DateTimeField(auto_now=True, help_text='created time')),
                ('updated_at', models.DateTimeField(auto_now_add=True, help_text='updated time')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=512, unique=True)),
            ],
            options={
                'verbose_name_plural': 'campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('created_at', models.DateTimeField(auto_now=True, help_text='created time')),
                ('updated_at', models.DateTimeField(auto_now_add=True, help_text='updated time')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True)),
                ('full_name', models.CharField(max_length=512, unique=True)),
                ('role', models.CharField(choices=[('Trainer', 'Trainer'), ('Lead', 'Lead')], max_length=10)),
                ('campaign', models.ManyToManyField(to='tms.campaign')),
            ],
            options={
                'verbose_name_plural': 'members',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('created_at', models.DateTimeField(auto_now=True, help_text='created time')),
                ('updated_at', models.DateTimeField(auto_now_add=True, help_text='updated time')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=512)),
                ('role', models.CharField(choices=[('IN PROGRESS', 'IN PROGRESS'), ('SUBMITTED', 'SUBMITTED'), ('REVIEWED', 'REVIEWED')], max_length=15)),
                ('score', models.FloatField()),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewer', to='tms.member')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainer', to='tms.member')),
            ],
            options={
                'verbose_name_plural': 'tasks',
                'ordering': ['-created_at'],
            },
        ),
    ]
