# Generated by Django 5.1 on 2024-09-02 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='role',
            new_name='status',
        ),
    ]
