# Generated by Django 5.1 on 2024-09-02 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tms', '0003_alter_member_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='campaign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaign', to='tms.campaign'),
        ),
        migrations.AlterField(
            model_name='task',
            name='score',
            field=models.FloatField(null=True),
        ),
    ]
