# Generated by Django 5.1 on 2024-09-02 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tms", "0005_alter_task_unique_together_task_unique"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="task",
            name="unique",
        ),
    ]
